package com.application.habittracker.theme.color_palettes

import androidx.compose.ui.graphics.Color
import com.application.habittracker.theme.MaterialThemeColorsPalette

object BlueColorBase : MaterialThemeColorsPalette {
    override val primaryLight                  = Color(0xFF0057CC)
    override val onPrimaryLight                = Color(0xFFFFFFFF)
    override val primaryContainerLight         = Color(0xFFD6E4FF)
    override val onPrimaryContainerLight       = Color(0xFF001946)
    override val secondaryLight                = Color(0xFF535F70)
    override val onSecondaryLight              = Color(0xFFFFFFFF)
    override val secondaryContainerLight       = Color(0xFFD7E3F7)
    override val onSecondaryContainerLight     = Color(0xFF101C2B)
    override val tertiaryLight                 = Color(0xFF6B5778)
    override val onTertiaryLight               = Color(0xFFFFFFFF)
    override val tertiaryContainerLight        = Color(0xFFF3DAFF)
    override val onTertiaryContainerLight      = Color(0xFF251431)
    override val errorLight                    = Color(0xFFBA1A1A)
    override val onErrorLight                  = Color(0xFFFFFFFF)
    override val errorContainerLight           = Color(0xFFFFDAD6)
    override val onErrorContainerLight         = Color(0xFF410002)
    override val backgroundLight               = Color(0xFFF8F9FF)
    override val onBackgroundLight             = Color(0xFF191C20)
    override val surfaceLight                  = Color(0xFFF8F9FF)
    override val onSurfaceLight                = Color(0xFF191C20)
    override val surfaceVariantLight           = Color(0xFFDDE3ED)
    override val onSurfaceVariantLight         = Color(0xFF41474D)
    override val outlineLight                  = Color(0xFF71787E)
    override val outlineVariantLight           = Color(0xFFC1C7CE)
    override val scrimLight                    = Color(0xFF000000)
    override val inverseSurfaceLight           = Color(0xFF2E3135)
    override val inverseOnSurfaceLight         = Color(0xFFEFF0F7)
    override val inversePrimaryLight           = Color(0xFFA8C8FF)
    override val surfaceDimLight               = Color(0xFFD9DADF)
    override val surfaceBrightLight            = Color(0xFFF8F9FF)
    override val surfaceContainerLowestLight   = Color(0xFFFFFFFF)
    override val surfaceContainerLowLight      = Color(0xFFF2F3F8)
    override val surfaceContainerLight         = Color(0xFFEDEDF3)
    override val surfaceContainerHighLight     = Color(0xFFE7E8ED)
    override val surfaceContainerHighestLight  = Color(0xFFE1E2E8)

    override val primaryDark                   = Color(0xFFA8C8FF)
    override val onPrimaryDark                 = Color(0xFF002D6E)
    override val primaryContainerDark          = Color(0xFF00429C)
    override val onPrimaryContainerDark        = Color(0xFFD6E4FF)
    override val secondaryDark                 = Color(0xFFBBC8DA)
    override val onSecondaryDark               = Color(0xFF253141)
    override val secondaryContainerDark        = Color(0xFF3B4858)
    override val onSecondaryContainerDark      = Color(0xFFD7E3F7)
    override val tertiaryDark                  = Color(0xFFD9BEE7)
    override val onTertiaryDark                = Color(0xFF3B2948)
    override val tertiaryContainerDark         = Color(0xFF524060)
    override val onTertiaryContainerDark       = Color(0xFFF3DAFF)
    override val errorDark                     = Color(0xFFFFB4AB)
    override val onErrorDark                   = Color(0xFF690005)
    override val errorContainerDark            = Color(0xFF93000A)
    override val onErrorContainerDark          = Color(0xFFFFDAD6)
    override val backgroundDark                = Color(0xFF111318)
    override val onBackgroundDark              = Color(0xFFE1E2E8)
    override val surfaceDark                   = Color(0xFF111318)
    override val onSurfaceDark                 = Color(0xFFE1E2E8)
    override val surfaceVariantDark            = Color(0xFF41474D)
    override val onSurfaceVariantDark          = Color(0xFFC1C7CE)
    override val outlineDark                   = Color(0xFF8B9198)
    override val outlineVariantDark            = Color(0xFF41474D)
    override val scrimDark                     = Color(0xFF000000)
    override val inverseSurfaceDark            = Color(0xFFE1E2E8)
    override val inverseOnSurfaceDark          = Color(0xFF2E3135)
    override val inversePrimaryDark            = Color(0xFF0057CC)
    override val surfaceDimDark                = Color(0xFF111318)
    override val surfaceBrightDark             = Color(0xFF36393E)
    override val surfaceContainerLowestDark    = Color(0xFF0B0E13)
    override val surfaceContainerLowDark       = Color(0xFF191C20)
    override val surfaceContainerDark          = Color(0xFF1D2024)
    override val surfaceContainerHighDark      = Color(0xFF282A2F)
    override val surfaceContainerHighestDark   = Color(0xFF323539)
}
