package com.application.habittracker.theme.color_palettes

import androidx.compose.ui.graphics.Color
import com.application.habittracker.theme.MaterialThemeColorsPalette

object OrangeColorBase : MaterialThemeColorsPalette {
    override val primaryLight                  = Color(0xFF8B5000)
    override val onPrimaryLight                = Color(0xFFFFFFFF)
    override val primaryContainerLight         = Color(0xFFFFDDB5)
    override val onPrimaryContainerLight       = Color(0xFF2C1600)
    override val secondaryLight                = Color(0xFF725A42)
    override val onSecondaryLight              = Color(0xFFFFFFFF)
    override val secondaryContainerLight       = Color(0xFFFFDDB5)
    override val onSecondaryContainerLight     = Color(0xFF291400)
    override val tertiaryLight                 = Color(0xFF576134)
    override val onTertiaryLight               = Color(0xFFFFFFFF)
    override val tertiaryContainerLight        = Color(0xFFDBE6AC)
    override val onTertiaryContainerLight      = Color(0xFF141D00)
    override val errorLight                    = Color(0xFFBA1A1A)
    override val onErrorLight                  = Color(0xFFFFFFFF)
    override val errorContainerLight           = Color(0xFFFFDAD6)
    override val onErrorContainerLight         = Color(0xFF410002)
    override val backgroundLight               = Color(0xFFFFF8F4)
    override val onBackgroundLight             = Color(0xFF201A13)
    override val surfaceLight                  = Color(0xFFFFF8F4)
    override val onSurfaceLight                = Color(0xFF201A13)
    override val surfaceVariantLight           = Color(0xFFF0E0CF)
    override val onSurfaceVariantLight         = Color(0xFF4F4539)
    override val outlineLight                  = Color(0xFF81715E)
    override val outlineVariantLight           = Color(0xFFD4C4B3)
    override val scrimLight                    = Color(0xFF000000)
    override val inverseSurfaceLight           = Color(0xFF362F27)
    override val inverseOnSurfaceLight         = Color(0xFFFBEFE4)
    override val inversePrimaryLight           = Color(0xFFFFB869)
    override val surfaceDimLight               = Color(0xFFE4D8CC)
    override val surfaceBrightLight            = Color(0xFFFFF8F4)
    override val surfaceContainerLowestLight   = Color(0xFFFFFFFF)
    override val surfaceContainerLowLight      = Color(0xFFFEF2E7)
    override val surfaceContainerLight         = Color(0xFFF8ECE1)
    override val surfaceContainerHighLight     = Color(0xFFF2E6DB)
    override val surfaceContainerHighestLight  = Color(0xFFEDE1D6)

    override val primaryDark                   = Color(0xFFFFB869)
    override val onPrimaryDark                 = Color(0xFF4A2800)
    override val primaryContainerDark          = Color(0xFF6A3C00)
    override val onPrimaryContainerDark        = Color(0xFFFFDDB5)
    override val secondaryDark                 = Color(0xFFE2C09F)
    override val onSecondaryDark               = Color(0xFF412C16)
    override val secondaryContainerDark        = Color(0xFF5A422A)
    override val onSecondaryContainerDark      = Color(0xFFFFDDB5)
    override val tertiaryDark                  = Color(0xFFBFCB92)
    override val onTertiaryDark                = Color(0xFF2A3308)
    override val tertiaryContainerDark         = Color(0xFF404A1D)
    override val onTertiaryContainerDark       = Color(0xFFDBE6AC)
    override val errorDark                     = Color(0xFFFFB4AB)
    override val onErrorDark                   = Color(0xFF690005)
    override val errorContainerDark            = Color(0xFF93000A)
    override val onErrorContainerDark          = Color(0xFFFFDAD6)
    override val backgroundDark                = Color(0xFF17110B)
    override val onBackgroundDark              = Color(0xFFEDE1D6)
    override val surfaceDark                   = Color(0xFF17110B)
    override val onSurfaceDark                 = Color(0xFFEDE1D6)
    override val surfaceVariantDark            = Color(0xFF4F4539)
    override val onSurfaceVariantDark          = Color(0xFFD4C4B3)
    override val outlineDark                   = Color(0xFF9C8E7D)
    override val outlineVariantDark            = Color(0xFF4F4539)
    override val scrimDark                     = Color(0xFF000000)
    override val inverseSurfaceDark            = Color(0xFFEDE1D6)
    override val inverseOnSurfaceDark          = Color(0xFF362F27)
    override val inversePrimaryDark            = Color(0xFF8B5000)
    override val surfaceDimDark                = Color(0xFF17110B)
    override val surfaceBrightDark             = Color(0xFF3E362D)
    override val surfaceContainerLowestDark    = Color(0xFF110C06)
    override val surfaceContainerLowDark       = Color(0xFF201A13)
    override val surfaceContainerDark          = Color(0xFF241E16)
    override val surfaceContainerHighDark      = Color(0xFF2F2820)
    override val surfaceContainerHighestDark   = Color(0xFF3A322A)
}
