package com.application.habittracker.theme.color_palettes

import androidx.compose.ui.graphics.Color
import com.application.habittracker.theme.MaterialThemeColorsPalette

object PurpleColorBase : MaterialThemeColorsPalette {
    override val primaryLight                  = Color(0xFF6750A4)
    override val onPrimaryLight                = Color(0xFFFFFFFF)
    override val primaryContainerLight         = Color(0xFFEADDFF)
    override val onPrimaryContainerLight       = Color(0xFF21005D)
    override val secondaryLight                = Color(0xFF625B71)
    override val onSecondaryLight              = Color(0xFFFFFFFF)
    override val secondaryContainerLight       = Color(0xFFE8DEF8)
    override val onSecondaryContainerLight     = Color(0xFF1D192B)
    override val tertiaryLight                 = Color(0xFF7D5260)
    override val onTertiaryLight               = Color(0xFFFFFFFF)
    override val tertiaryContainerLight        = Color(0xFFFFD8E4)
    override val onTertiaryContainerLight      = Color(0xFF31111D)
    override val errorLight                    = Color(0xFFBA1A1A)
    override val onErrorLight                  = Color(0xFFFFFFFF)
    override val errorContainerLight           = Color(0xFFFFDAD6)
    override val onErrorContainerLight         = Color(0xFF410002)
    override val backgroundLight               = Color(0xFFFFFBFE)
    override val onBackgroundLight             = Color(0xFF1C1B1F)
    override val surfaceLight                  = Color(0xFFFFFBFE)
    override val onSurfaceLight                = Color(0xFF1C1B1F)
    override val surfaceVariantLight           = Color(0xFFE7E0EC)
    override val onSurfaceVariantLight         = Color(0xFF49454F)
    override val outlineLight                  = Color(0xFF79747E)
    override val outlineVariantLight           = Color(0xFFCAC4D0)
    override val scrimLight                    = Color(0xFF000000)
    override val inverseSurfaceLight           = Color(0xFF313033)
    override val inverseOnSurfaceLight         = Color(0xFFF4EFF4)
    override val inversePrimaryLight           = Color(0xFFD0BCFF)
    override val surfaceDimLight               = Color(0xFFDED8E1)
    override val surfaceBrightLight            = Color(0xFFFFFBFE)
    override val surfaceContainerLowestLight   = Color(0xFFFFFFFF)
    override val surfaceContainerLowLight      = Color(0xFFF7F2FA)
    override val surfaceContainerLight         = Color(0xFFF3EDF7)
    override val surfaceContainerHighLight     = Color(0xFFECE6F0)
    override val surfaceContainerHighestLight  = Color(0xFFE6E0E9)

    override val primaryDark                   = Color(0xFFD0BCFF)
    override val onPrimaryDark                 = Color(0xFF381E72)
    override val primaryContainerDark          = Color(0xFF4F378B)
    override val onPrimaryContainerDark        = Color(0xFFEADDFF)
    override val secondaryDark                 = Color(0xFFCCC2DC)
    override val onSecondaryDark               = Color(0xFF332D41)
    override val secondaryContainerDark        = Color(0xFF4A4458)
    override val onSecondaryContainerDark      = Color(0xFFE8DEF8)
    override val tertiaryDark                  = Color(0xFFEFB8C8)
    override val onTertiaryDark                = Color(0xFF492532)
    override val tertiaryContainerDark         = Color(0xFF633B48)
    override val onTertiaryContainerDark       = Color(0xFFFFD8E4)
    override val errorDark                     = Color(0xFFFFB4AB)
    override val onErrorDark                   = Color(0xFF690005)
    override val errorContainerDark            = Color(0xFF93000A)
    override val onErrorContainerDark          = Color(0xFFFFDAD6)
    override val backgroundDark                = Color(0xFF1C1B1F)
    override val onBackgroundDark              = Color(0xFFE6E1E5)
    override val surfaceDark                   = Color(0xFF1C1B1F)
    override val onSurfaceDark                 = Color(0xFFE6E1E5)
    override val surfaceVariantDark            = Color(0xFF49454F)
    override val onSurfaceVariantDark          = Color(0xFFCAC4D0)
    override val outlineDark                   = Color(0xFF938F99)
    override val outlineVariantDark            = Color(0xFF49454F)
    override val scrimDark                     = Color(0xFF000000)
    override val inverseSurfaceDark            = Color(0xFFE6E1E5)
    override val inverseOnSurfaceDark          = Color(0xFF313033)
    override val inversePrimaryDark            = Color(0xFF6750A4)
    override val surfaceDimDark                = Color(0xFF1C1B1F)
    override val surfaceBrightDark             = Color(0xFF3B383E)
    override val surfaceContainerLowestDark    = Color(0xFF0F0D13)
    override val surfaceContainerLowDark       = Color(0xFF1D1B20)
    override val surfaceContainerDark          = Color(0xFF211F26)
    override val surfaceContainerHighDark      = Color(0xFF2B2930)
    override val surfaceContainerHighestDark   = Color(0xFF36343B)
}
