package com.application.habittracker.theme.color_palettes

import androidx.compose.ui.graphics.Color
import com.application.habittracker.theme.MaterialThemeColorsPalette

object RedColorBase : MaterialThemeColorsPalette {
    override val primaryLight                  = Color(0xFF904A43)
    override val onPrimaryLight                = Color(0xFFFFFFFF)
    override val primaryContainerLight         = Color(0xFFFFDAD6)
    override val onPrimaryContainerLight       = Color(0xFF3B0907)
    override val secondaryLight                = Color(0xFF775652)
    override val onSecondaryLight              = Color(0xFFFFFFFF)
    override val secondaryContainerLight       = Color(0xFFFFDAD6)
    override val onSecondaryContainerLight     = Color(0xFF2C1513)
    override val tertiaryLight                 = Color(0xFF735B2E)
    override val onTertiaryLight               = Color(0xFFFFFFFF)
    override val tertiaryContainerLight        = Color(0xFFFFDEA0)
    override val onTertiaryContainerLight      = Color(0xFF271900)
    override val errorLight                    = Color(0xFFBA1A1A)
    override val onErrorLight                  = Color(0xFFFFFFFF)
    override val errorContainerLight           = Color(0xFFFFDAD6)
    override val onErrorContainerLight         = Color(0xFF410002)
    override val backgroundLight               = Color(0xFFFFF8F7)
    override val onBackgroundLight             = Color(0xFF22191A)
    override val surfaceLight                  = Color(0xFFFFF8F7)
    override val onSurfaceLight                = Color(0xFF22191A)
    override val surfaceVariantLight           = Color(0xFFF5DDDA)
    override val onSurfaceVariantLight         = Color(0xFF534342)
    override val outlineLight                  = Color(0xFF857371)
    override val outlineVariantLight           = Color(0xFFD8C2BF)
    override val scrimLight                    = Color(0xFF000000)
    override val inverseSurfaceLight           = Color(0xFF382E2E)
    override val inverseOnSurfaceLight         = Color(0xFFFFEDEB)
    override val inversePrimaryLight           = Color(0xFFFFB3AC)
    override val surfaceDimLight               = Color(0xFFE8D6D5)
    override val surfaceBrightLight            = Color(0xFFFFF8F7)
    override val surfaceContainerLowestLight   = Color(0xFFFFFFFF)
    override val surfaceContainerLowLight      = Color(0xFFFFF0EF)
    override val surfaceContainerLight         = Color(0xFFFCEAE9)
    override val surfaceContainerHighLight     = Color(0xFFF6E4E3)
    override val surfaceContainerHighestLight  = Color(0xFFF1DEDD)

    override val primaryDark                   = Color(0xFFFFB3AC)
    override val onPrimaryDark                 = Color(0xFF561E1A)
    override val primaryContainerDark          = Color(0xFF73332E)
    override val onPrimaryContainerDark        = Color(0xFFFFDAD6)
    override val secondaryDark                 = Color(0xFFE7BDB8)
    override val onSecondaryDark               = Color(0xFF442928)
    override val secondaryContainerDark        = Color(0xFF5D3F3D)
    override val onSecondaryContainerDark      = Color(0xFFFFDAD6)
    override val tertiaryDark                  = Color(0xFFE2C27D)
    override val onTertiaryDark                = Color(0xFF3E2D04)
    override val tertiaryContainerDark         = Color(0xFF574419)
    override val onTertiaryContainerDark       = Color(0xFFFFDEA0)
    override val errorDark                     = Color(0xFFFFB4AB)
    override val onErrorDark                   = Color(0xFF690005)
    override val errorContainerDark            = Color(0xFF93000A)
    override val onErrorContainerDark          = Color(0xFFFFDAD6)
    override val backgroundDark                = Color(0xFF18100F)
    override val onBackgroundDark              = Color(0xFFF1DEDD)
    override val surfaceDark                   = Color(0xFF18100F)
    override val onSurfaceDark                 = Color(0xFFF1DEDD)
    override val surfaceVariantDark            = Color(0xFF534342)
    override val onSurfaceVariantDark          = Color(0xFFD8C2BF)
    override val outlineDark                   = Color(0xFFA08C8A)
    override val outlineVariantDark            = Color(0xFF534342)
    override val scrimDark                     = Color(0xFF000000)
    override val inverseSurfaceDark            = Color(0xFFF1DEDD)
    override val inverseOnSurfaceDark          = Color(0xFF382E2E)
    override val inversePrimaryDark            = Color(0xFF904A43)
    override val surfaceDimDark                = Color(0xFF18100F)
    override val surfaceBrightDark             = Color(0xFF3F3434)
    override val surfaceContainerLowestDark    = Color(0xFF120A09)
    override val surfaceContainerLowDark       = Color(0xFF22191A)
    override val surfaceContainerDark          = Color(0xFF261D1D)
    override val surfaceContainerHighDark      = Color(0xFF312828)
    override val surfaceContainerHighestDark   = Color(0xFF3C3232)
}
